#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'gamepadui'

def options(opt):
	# stub
	return

def configure(conf):
	conf.env.append_unique('DEFINES',[
			'GAMEPADUI_DLL',
			'GAMEPADUI_GAME_HL2',
			'GAMEPADUI_GAME_EPISODIC',
			'GAMEPADUI_GAME_EZ',
			'GAMEPADUI_GAME_EZ2',
			'GAMEPADUI_ENABLE_BONUSMAPS',
			'VERSION_SAFE_STEAM_API_INTERFACES',
			'MAPBASE',
	])

	game = conf.options.GAMES
	conf.env.GAMES = game

def build(bld):
	source = [
		'../../public/vgui_controls/vgui_controls.cpp',
		'../../common/language.cpp',
		'../../common/img_png_loader.cpp',
		'gamepadui_achievements.cpp',
		'gamepadui_basepanel.cpp',
		'gamepadui_button.cpp',
		'gamepadui_frame.cpp',
		'gamepadui_genericconfirmation.cpp',
		'gamepadui_genericframes.cpp',
		'gamepadui_interface.cpp',
		'gamepadui_mainmenu.cpp',
		'gamepadui_newgame.cpp',
		'gamepadui_savegame.cpp',
		'gamepadui_options.cpp',
		'gamepadui_scrollbar.cpp',
		'gamepadui_util.cpp',
		'gamepadui_bonusmaps.cpp',
	]

	includes = [
		'.',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
	] + bld.env.INCLUDES_SDL2

	defines = []

	libs = [
		'tier0',
		'vgui_controls',
		'matsys_controls',
		'tier1',
		'tier2',
		'tier3',
		'vstdlib',
		'choreoobjects',
		'steam_api',
		'bitmap',
		'mathlib',
		'vtf',
		'SDL2',
		'PNG',
	]

	install_path = bld.env.PREFIX
	if bld.env.DEST_OS != 'android':
		install_path += '/'+bld.env.GAMES+'/bin'

	if bld.env.DEST_OS == 'android':
		libs += ['ANDROID_SUPPORT']

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

